apiVersion: apps/v1
kind: Deployment
metadata:
  name: MICROSERVICE_NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MICROSERVICE_NAME_PLACEHOLDER
  template:
    metadata:
      labels:
        app: MICROSERVICE_NAME_PLACEHOLDER
    spec:
      containers:
      - name: MICROSERVICE_NAME_PLACEHOLDER
        image: davidanthonyvarley/MICROSERVICE_NAME_PLACEHOLDER:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: PORT_PLACEHOLDER
