apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-http1p1-helloworld-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-http1p1-helloworld-server
  template:
    metadata:
      labels:
        app: py-http1p1-helloworld-server
    spec:
      containers:
      - name: py-http1p1-helloworld-server
        image: davidanthonyvarley/py-http1p1-helloworld-server:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 30080
