apiVersion: apps/v1
kind: Deployment
metadata:
  name: MICROSERVICE_NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MICROSERVICE_NAME_PLACEHOLDER
  template:
    metadata:
      labels:
        app: MICROSERVICE_NAME_PLACEHOLDER
        
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: http3-tls-cert
      containers:
      - name: MICROSERVICE_NAME_PLACEHOLDER
        image: davidanthonyvarley/MICROSERVICE_NAME_PLACEHOLDER:latest

        command: ["python3"]
        args:
          - MICROSERVICE_NAME_PLACEHOLDER.py
          - --cert=/certs/tls.crt
          - --key=/certs/tls.key
        volumeMounts:
          - name: cert-volume
            mountPath: /certs

        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: PORT_PLACEHOLDER

      
