apiVersion: v1
kind: Service
metadata:
  name: MICROSERVICE_NAME_PLACEHOLDER
spec:
  type: NodePort
  selector:
    app: MICROSERVICE_NAME_PLACEHOLDER
  ports:
  - name: https-tcp
    protocol: TCP
    port: PORT_PLACEHOLDER      
    targetPort: PORT_PLACEHOLDER  
    nodePort: PORT_PLACEHOLDER
  
  - name: https-quic
    protocol: UDP
    port: PORT_PLACEHOLDER      
    targetPort: PORT_PLACEHOLDER  
    nodePort: PORT_PLACEHOLDER
