apiVersion: v1
kind: Service
metadata:
  name: py-http1p1-helloworld-server
spec:
  type: NodePort
  selector:
    app: py-http1p1-helloworld-server
  ports:
  - port: 30080       # cluster port (can stay as is)
    targetPort: 30080  # container port in pod
