apiVersion: v1
kind: Service
metadata:
  name: MICROSERVICE_NAME_PLACEHOLDER
spec:
  type: NodePort
  selector:
    app: MICROSERVICE_NAME_PLACEHOLDER
  ports:
  - port: 30080       # cluster port (can stay as is)
    targetPort: 30080  # container port in pod
