apiVersion: v1
kind: Service
metadata:
  name: MICROSERVICE_NAME_PLACEHOLDER
spec:
  type: NodePort
  selector:
    app: MICROSERVICE_NAME_PLACEHOLDER
  ports:
  - port: PORT_PLACEHOLDER      
    targetPort: PORT_PLACEHOLDER  
    NodePort: PORT_PLACEHOLDER
