apiVersion: apps/v1
kind: Deployment
metadata:
  name: small-sized-data-server--1mb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: small-sized-data-server--1mb
  template:
    metadata:
      labels:
        app: small-sized-data-server--1mb
    spec:
      containers:
      - name: subscriber
        image: davidAnthonyVarley/small-sized-data-server--1mb:latest # The image from your Dockerfile [cite: 1]
        imagePullPolicy: IfNotPresent
        env:
        - name: SUB_ID
          value: "subA" 
        volumeMounts:
        - name: testing-data-volume
          mountPath: /mnt/testing-data
          readOnly: true
      volumes:
      - name: testing-data-volume
        persistentVolumeClaim:
          claimName: testing-data-pvc