apiVersion: v1
kind: Service
metadata:
  name: small-sized-data-server--service
  namespace: default
  labels:
    app: small-sized-data-server--service
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: small-sized-data-server--1mb
  type: ClusterIP