apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoycbr-httpfilter-sidecar  # Changed from envoyCBR-HTTPFilter-Service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoycbr-httpfilter-sidecar # MUST match the Service selector
  template:
    metadata:
      labels:
        app: envoycbr-httpfilter-sidecar
    spec:
      containers:
      - name: processor
        image: davidAnthonyVarley/envoy-ext-proc:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9002
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"