apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-7-100mb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-7-100mb
  template:
    metadata:
      labels:
        app: subscriber-7-100mb
    spec:
      containers:
      - name: subscriber
        image: davidAnthonyVarley/large-sized-data--server:latest # The image from your Dockerfile [cite: 1]
        env:
        - name: SUB_ID
          value: "7" # Tells the pod to use ID 7 and bind to 'sub.7'
        volumeMounts:
        - name: data-volume
          mountPath: /data/test_files
          readOnly: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: test-data-pvc