apiVersion: v1
kind: Service
metadata:
  name: subscriber-7-100mb-service
  namespace: default
  labels:
    app: subscriber-7-100mb-service
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: subscriber-7-100mb
  type: ClusterIP