apiVersion: v1
kind: Service
metadata:
  name: subscriber-pod
  namespace: default
  labels:
    app: subscriber-pod
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: subscriber-pod
  type: ClusterIP