apiVersion: v1
kind: Service
metadata:
  name: http-1p1-helloworld
  namespace: default
  labels:
    app: http-1p1-helloworld
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: http-1p1-helloworld
  type: ClusterIP