apiVersion: apps/v1
kind: Deployment
metadata:
  name: pst-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pst-pod
  template:
    metadata:
      labels:
        app: pst-pod
        
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: example-cert
      containers:
      - name: pst-pod
        image: davidAnthonyVarley/pst-pod:latest

        command: ["python3--------------------------needs to change to java command + certs?-------"]
        volumeMounts:
          - name: cert-volume
            mountPath: /certs

        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081


      
