
apiVersion: v1
kind: Service
metadata:
  name: pst-service
  namespace: default
  labels:
    app: pst-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pst-pod
  type: ClusterIP